version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    networks:
      - salt
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_CUSTOM_LDIF_DIR=/ldif_import
      - BITNAMI_DEBUG=true
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - './ldif:/ldif_import'

volumes:
  openldap_data:
    driver: local

networks:
  salt:
    external: true
